---
- hosts: glance-api[0]
  sudo: True
  vars:
    cirros_url: http://cdn.download.cirros-cloud.net/0.3.1/cirros-0.3.1-x86_64-disk.img
    filename: cirros-0.3.1
  roles:
    - openstack/keystone/_global
  post_tasks:
    - name: download cirros
      get_url:
        url={{ cirros_url }}
        dest=/tmp/{{ filename }}

    - name: upload to glance
      glance:
        name={{ filename }}
        file=/tmp/{{ filename }}
        disk_format=qcow2
        container_format=bare
        is_public=True
        auth_url={{ keystone_admin_url }}
        username={{ keystone_admin_username }}
        password={{ keystone_admin_password }}
        tenant_name={{ keystone_admin_tenant_name }}
