---
- hosts: all
  sudo: True
  roles:
    - ubi-common
  tags:
    - ubi-common

- hosts: mysql
  sudo: True
  roles:
    - os-mysql
  tags:
    - mysql

- hosts: rabbitmq
  sudo: True
  roles:
    - rabbitmq
  tags:
    - rabbitmq

- hosts: keystone
  sudo: True
  roles:
    - os-keystone
  tags:
    - keystone

- hosts: nova-api
  sudo: True
  roles:
    - role: os-nova
      service: nova-api
  tags:
    - nova
    - nova-api

- hosts: nova-scheduler
  sudo: True
  roles:
    - role: os-nova
      service: nova-network
  tags:
    - nova
    - nova-scheduler

- hosts: cinder-api
  sudo: True
  roles:
    - role: os-cinder
      service: cinder-api
  tags:
    - cinder
    - cinder-api

- hosts: cinder-scheduler
  sudo: True
  roles:
    - role: os-cinder
      service: cinder-scheduler
  tags:
    - cinder
    - cinder-scheduler

- hosts: cinder-volume
  sudo: True
  roles:
    - role: os-cinder
      service: cinder-volume
  tags:
    - cinder
    - cinder-volume

- hosts: glance-api
  sudo: True
  roles:
    - role: os-glance
      service: glance-api
  tags:
    - glance
    - glance-api

- hosts: glance-registry
  sudo: True
  roles:
    - role: os-glance
      service: glance-registry
  tags:
    - glance
    - glance-registry

- hosts: dashboard
  sudo: True
  roles:
    - os-horizon
  tags:
    - horizon

- hosts: compute
  sudo: True
  roles:
    - role: os-nova
      service: nova-compute
    - role: os-nova
      service: nova-network
  tags:
    - nova
    - nova-compute
