---
- hosts: all
  sudo: True
  roles:
    - ubi-common
  tags:
    - ubi-common

- hosts: mysql
  sudo: True
  roles:
    - openstack/mysql
  tags:
    - mysql

- hosts: rabbitmq
  sudo: True
  roles:
    - openstack/rabbitmq
  tags:
    - rabbitmq

- hosts: keystone
  sudo: True
  roles:
    - role: openstack/keystone
      do: install
  tags:
    - keystone

- hosts: nova-api
  sudo: True
  roles:
    - role: openstack/nova
      do: install
      service: nova-api
  tags:
    - nova
    - nova-api

- hosts: nova-scheduler
  sudo: True
  roles:
    - role: openstack/nova
      do: install
      service: nova-network
  tags:
    - nova
    - nova-scheduler

- hosts: cinder-api
  sudo: True
  roles:
    - role: openstack/cinder
      do: install
      service: cinder-api
  tags:
    - cinder
    - cinder-api

- hosts: cinder-scheduler
  sudo: True
  roles:
    - role: openstack/cinder
      do: install
      service: cinder-scheduler
  tags:
    - cinder
    - cinder-scheduler

- hosts: cinder-volume
  sudo: True
  roles:
    - role: openstack/cinder
      do: install
      service: cinder-volume
  tags:
    - cinder
    - cinder-volume

- hosts: glance-api
  sudo: True
  roles:
    - role: openstack/glance
      do: install
      service: glance-api
  tags:
    - glance
    - glance-api

- hosts: glance-registry
  sudo: True
  roles:
    - role: openstack/glance
      do: install
      service: glance-registry
  tags:
    - glance
    - glance-registry

- hosts: dashboard
  sudo: True
  roles:
    - openstack/horizon
  tags:
    - horizon

- hosts: compute
  sudo: True
  roles:
    - role: openstack/nova
      do: install
      service: nova-compute
    - role: openstack/nova
      do: install
      service: nova-network
  tags:
    - nova
    - nova-compute
