---
- hosts: all
  sudo: True
  roles:
    - ubi-common
  tags:
    - ubi-common

- hosts: mysql
  sudo: True
  roles:
    - openstack/mysql
  tags:
    - mysql

- hosts: rabbitmq
  sudo: True
  roles:
    - openstack/rabbitmq
  tags:
    - rabbitmq

- hosts: keystone
  sudo: True
  roles:
    - openstack/keystone
  tags:
    - keystone

- hosts: nova-api
  sudo: True
  roles:
    - openstack/nova-api
  tags:
    - nova
    - nova-api

- hosts: nova-scheduler
  sudo: True
  roles:
    - openstack/nova-scheduler
  tags:
    - nova
    - nova-scheduler

- hosts: cinder-api
  sudo: True
  roles:
    - openstack/cinder-api
  tags:
    - cinder
    - cinder-api

- hosts: cinder-scheduler
  sudo: True
  roles:
    - openstack/cinder-scheduler
  tags:
    - cinder
    - cinder-scheduler

- hosts: cinder-volume
  sudo: True
  roles:
    - openstack/cinder-volume
  tags:
    - cinder
    - cinder-volume

- hosts: glance-api
  sudo: True
  roles:
    - openstack/glance-api
  tags:
    - glance
    - glance-api

- hosts: glance-registry
  sudo: True
  roles:
    - openstack/glance-registry
  tags:
    - glance
    - glance-registry

- hosts: dashboard
  sudo: True
  roles:
    - openstack/horizon
  tags:
    - horizon

- hosts: compute
  sudo: True
  roles:
    - openstack/nova-compute
    - openstack/nova-network
  tags:
    - nova
    - nova-compute
